### ISSUE TITLE
perf_event

### ISSUE THREAD

**Issue by liyan-ah** [mrproliu/my_ebpf_test#1]
从：[How to attach `perf_events`? #548](https://github.com/cilium/ebpf/discussions/548)。这块有什么进展么？代码能跑通么？最近也在进行 ebpf continuous profiling 的项目，也卡在这个实现了。

**Comment by mrproliu** [comment]
Please check the https://github.com/mrproliu/my_ebpf_test/tree/main/perf, here is a full example and It works well.

**Comment by mrproliu** [comment]
Any update? If haven't I close it.
